"use client";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
type Module = { module: string; enabled: boolean; status: string; coverage?: Record<string, unknown>; stop_reason?: string | null };
type Investigation = { id: string; status: string; target: { type: string; name: string; [key: string]: unknown }; purpose: string; scope_modules: string[]; expansion_policy: string; max_relation_depth: number; entities?: unknown[]; claims?: unknown[]; modules?: Module[] };
const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
export default function InvestigationPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [investigation, setInvestigation] = useState<Investigation | null>(null); const [error, setError] = useState("");
  useEffect(() => { fetch(`${API_BASE}/api/v1/investigations/${id}`).then(async (response) => { const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(payload?.detail || "Fant ikke undersøkelsen."); setInvestigation(payload); }).catch((caught) => setError(caught instanceof Error ? caught.message : "Kunne ikke laste undersøkelsen.")); }, [id]);
  if (error) return <main className="detail-shell"><a className="back-link" href="/">← Ny undersøkelse</a><div className="state-card"><h1>Kunne ikke åpne undersøkelsen</h1><p>{error}</p><button className="submit-button" onClick={() => router.refresh()}>Prøv igjen</button></div></main>;
  if (!investigation) return <main className="detail-shell"><p className="loading-state">Laster undersøkelse …</p></main>;
  const modules = investigation.modules || investigation.scope_modules.map((module) => ({ module, enabled: true, status: "NOT_STARTED" }));
  return <main className="detail-shell"><header className="detail-top"><a className="brand" href="/"><span className="brand-mark">A</span> ANALYSEN</a><a className="back-link" href="/">← Ny undersøkelse</a></header><div className="detail-heading"><p className="eyebrow">UNDERSØKELSE · {investigation.status}</p><h1>{investigation.target.name}</h1><p>{investigation.purpose}</p></div><section className="summary-grid"><div><span>Måltype</span><strong>{investigation.target.type}</strong></div><div><span>Ekspansjon</span><strong>{investigation.expansion_policy.replaceAll("_", " ")}</strong></div><div><span>Relasjonsdybde</span><strong>{investigation.max_relation_depth}</strong></div><div><span>ID</span><strong className="id-value">{investigation.id}</strong></div></section><section className="coverage-section"><div className="coverage-title"><div><p className="eyebrow">SCOPE OG DEKNING</p><h2>Valgte områder</h2></div><span className="not-running">Research er ikke startet</span></div><div className="coverage-list">{modules.map((item) => <div className="coverage-row" key={item.module}><div><strong>{item.module.replaceAll("_", " ")}</strong><span>{item.status === "NOT_STARTED" ? "Ikke undersøkt ennå" : item.status}</span></div><span className="status-dot" aria-label="Ikke startet" /></div>)}</div></section><div className="empty-note"><span>◌</span><div><strong>Ingen funn ennå</strong><p>Undersøkelsen er opprettet med tom dekning. Når orkestratoren blir tilgjengelig, vil dokumenter, claims og coverage vises her med kildehenvisning.</p></div></div></main>;
}
