"use client";

import { useParams } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import { ClaimState, EvidenceState, InvestigationDetail, ResearchStatus, formatApiDetail, formatDate, safeHttpUrl } from "../../types";

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
const activeStatuses: ResearchStatus[] = ["REQUESTED", "ENQUEUED", "RUNNING"];
const statusLabel: Record<ResearchStatus, string> = { NOT_STARTED: "Ingen registrert research-aktivitet", ACTIVITY_RECORDED: "Registrert aktivitet", REQUESTED: "Venter på købekreftelse", ENQUEUED: "Lagt på kø", RUNNING: "Pass kjører", COMPLETED: "Pass fullført", FAILED: "Pass feilet" };
const claimLabel: Record<string, string> = { SUPPORTED: "Støttet", PARTIALLY_SUPPORTED: "Delvis støttet", CONTRADICTED: "Motsagt", INSUFFICIENT_EVIDENCE: "Ikke verifisert", UNVERIFIED_LEAD: "Uverifisert spor" };

function valueText(value: unknown): string { if (typeof value === "string") return value; try { return JSON.stringify(value, null, 2); } catch { return String(value); } }
function coverageText(coverage: InvestigationDetail["modules"][number]["coverage"]): string { const parts = []; if (coverage.query_count !== undefined) parts.push(`${coverage.query_count} søk`); if (coverage.document_count !== undefined) parts.push(`${coverage.document_count} dokumenter`); if (coverage.providers?.length) parts.push(`kilder: ${coverage.providers.join(", ")}`); if (coverage.query_classes?.length) parts.push(`query classes: ${coverage.query_classes.join(", ")}`); const num = (v: number | undefined | null) => typeof v === "number" && v > 0; if (num(coverage.candidate_count)) parts.push(`kandidater: ${coverage.candidate_count}`); if (num(coverage.located_count)) parts.push(`lokalisert: ${coverage.located_count}`); if (num(coverage.restricted_count)) parts.push(`begrenset: ${coverage.restricted_count}`); if (num(coverage.fetched_count)) parts.push(`hentet: ${coverage.fetched_count}`); if (coverage.time_from || coverage.time_to) parts.push(`tidsrom: ${coverage.time_from ?? "–"}–${coverage.time_to ?? "–"}`); if (coverage.gaps?.length) parts.push(`mangler: ${coverage.gaps.join(", ")}`); if (coverage.unavailable_sources?.length) parts.push(`utilgjengelig: ${coverage.unavailable_sources.join(", ")}`); return parts.join(" · "); }
function lastResearchTimestamp(research: InvestigationDetail["research"]): string | null { return research.completed_at || research.started_at || research.enqueued_at || research.requested_at; }
type StepState = "done" | "active" | "todo" | "failed";
type FlowStep = { label: string; state: StepState; detail: string | null };
const TERMINAL_LEAD = ["COMPLETED", "BLOCKED", "FAILED"];
function researchSteps(research: InvestigationDetail["research"], leads: InvestigationDetail["leads"]): { steps: FlowStep[]; progress: number } {
  const begun = ["REQUESTED", "ENQUEUED", "RUNNING", "COMPLETED", "FAILED"].includes(research.status) || research.legacy_activity;
  const doneLeads = leads.filter((lead) => TERMINAL_LEAD.includes(lead.status)).length;
  const steps: FlowStep[] = [{ label: "Opprettet", state: "done", detail: null }];
  steps.push(!begun ? { label: "Lagt på kø", state: "todo", detail: null } : research.status === "REQUESTED" ? { label: "Lagt på kø", state: "active", detail: "Venter på købekreftelse" } : { label: "Lagt på kø", state: "done", detail: null });
  if (research.status === "COMPLETED" || research.status === "FAILED") steps.push({ label: "Under arbeid", state: "done", detail: leads.length ? `${doneLeads}/${leads.length} leads ferdig` : null });
  else if (research.status === "ENQUEUED" || research.status === "RUNNING") steps.push({ label: "Under arbeid", state: "active", detail: leads.length ? `${doneLeads}/${leads.length} leads ferdig` : "Pass kjører" });
  else steps.push({ label: "Under arbeid", state: "todo", detail: null });
  if (research.status === "COMPLETED") steps.push({ label: "Fullført", state: "done", detail: research.summary ? `${research.summary.executed} utført · ${research.summary.blocked} blokkert · ${research.summary.failed} feilet` : null });
  else if (research.status === "FAILED") steps.push({ label: "Feilet", state: "failed", detail: research.error_code || "Pass feilet" });
  else steps.push({ label: "Resultat", state: "todo", detail: null });
  const progress = leads.length ? Math.round((doneLeads / leads.length) * 100) : research.status === "COMPLETED" || research.status === "FAILED" ? 100 : begun ? 10 : 0;
  return { steps, progress };
}

export default function InvestigationPage() {
  const { id } = useParams<{ id: string }>();
  const [investigation, setInvestigation] = useState<InvestigationDetail | null>(null); const investigationRef = useRef<InvestigationDetail | null>(null); const requestGeneration = useRef(0); const currentId = useRef<string | null>(id); currentId.current = id; const [error, setError] = useState(""); const [stale, setStale] = useState(false); const [runStatus, setRunStatus] = useState(""); const [runOk, setRunOk] = useState(false); const [inflight, setInflight] = useState(false);
  const loadInvestigation = useCallback(async (signal?: AbortSignal) => {
    if (currentId.current !== id) return;
    const generation = ++requestGeneration.current;
    try { const response = await fetch(`${API_BASE}/api/v1/investigations/${id}`, { signal, cache: "no-store" }); const payload = await response.json().catch(() => null); if (signal?.aborted || generation !== requestGeneration.current || currentId.current !== id) return; if (!response.ok) throw new Error(formatApiDetail(payload?.detail) || "Fant ikke undersøkelsen."); if (!payload) throw new Error("API-et returnerte et ugyldig svar."); investigationRef.current = payload as InvestigationDetail; setInvestigation(payload as InvestigationDetail); setError(""); setStale(false); } catch (caught) { if (signal?.aborted || generation !== requestGeneration.current || currentId.current !== id) return; if (investigationRef.current) setStale(true); setError(caught instanceof Error ? caught.message : "Kunne ikke oppdatere undersøkelsen."); }
  }, [id]);
  useEffect(() => { currentId.current = id; investigationRef.current = null; setInvestigation(null); setError(""); setStale(false); setRunStatus(""); setInflight(false); const controller = new AbortController(); void loadInvestigation(controller.signal); return () => { ++requestGeneration.current; currentId.current = null; controller.abort(); }; }, [id, loadInvestigation]);
  useEffect(() => { if (!investigation || !activeStatuses.includes(investigation.research.status)) return; let cancelled = false; let timer: number; const poll = async () => { await loadInvestigation(); if (!cancelled) timer = window.setTimeout(() => void poll(), 2500); }; timer = window.setTimeout(() => void poll(), 2500); return () => { cancelled = true; window.clearTimeout(timer); }; }, [investigation, loadInvestigation]);
  async function startResearchPass() {
    if (!investigation || activeStatuses.includes(investigation.research.status) || inflight) return; setInflight(true); setRunStatus(""); setRunOk(false);
    try { const response = await fetch(`${API_BASE}/api/v1/investigations/${id}/research/run`, { method: "POST" }); const payload = await response.json().catch(() => null); if (currentId.current !== id) return; if (!response.ok) throw new Error(formatApiDetail(payload?.detail) || "Kunne ikke starte research."); setRunOk(true); setRunStatus(payload?.job_id ? `Research-pass lagt på kø (${payload.job_id}).` : "Research-pass lagt på kø."); } catch (caught) { if (currentId.current === id) setRunStatus(caught instanceof Error ? caught.message : "Noe gikk galt."); } finally { if (currentId.current === id) { setInflight(false); void loadInvestigation(); } }
  }
  if (error && !investigation) return <main className="detail-shell"><a className="back-link" href="/">← Ny undersøkelse</a><div className="state-card"><h1>Kunne ikke åpne undersøkelsen</h1><p>{error}</p><button className="submit-button" onClick={() => void loadInvestigation()}>Prøv igjen</button></div></main>;
  if (!investigation) return <main className="detail-shell"><p className="loading-state">Laster undersøkelse …</p></main>;
  const research = investigation.research; const isActive = activeStatuses.includes(research.status); const timestamp = lastResearchTimestamp(research); const flow = researchSteps(research, investigation.leads); const modules = investigation.modules || []; const enabledModules = modules.filter((item) => item.enabled); const completedModules = enabledModules.filter((item) => item.status === "COMPLETE").length;
  return <main className="detail-shell"><header className="detail-top"><a className="brand" href="/"><span className="brand-mark">A</span> ANALYSEN</a><a className="back-link" href="/">← Ny undersøkelse</a></header><div className="detail-heading"><p className="eyebrow">UNDERSØKELSE · {investigation.status}</p><h1>{investigation.target.name}</h1><p>{investigation.purpose}</p></div><section aria-label="Forløp"><p className="eyebrow">FORLØP</p><ol className="step-bar">{flow.steps.map((step) => <li key={step.label} className={`step step--${step.state}`} aria-current={step.state === "active" ? "step" : undefined}><strong>{step.label}</strong>{step.detail && <span>{step.detail}</span>}</li>)}</ol><div className="step-meter" role="progressbar" aria-valuenow={flow.progress} aria-valuemin={0} aria-valuemax={100} aria-label="Fremdrift"><i style={{ width: `${flow.progress}%` }} /></div></section><section className="summary-grid"><div><span>Måltype</span><strong>{investigation.target.type}</strong></div><div><span>Ekspansjon</span><strong>{investigation.expansion_policy.replaceAll("_", " ")}</strong></div><div><span>Relasjonsdybde</span><strong>{investigation.max_relation_depth}</strong></div><div><span>ID</span><strong className="id-value">{investigation.id}</strong></div></section>
    <section className="coverage-section"><div className="coverage-title"><div><p className="eyebrow">SCOPE OG DEKNING</p><h2>Valgte områder</h2></div><span className="worker-status">Sist registrerte research-status: {statusLabel[research.status]}<small>{formatDate(timestamp)}</small></span><a className="back-link" href={`/investigations/${id}/report`}>Dekningsrapport →</a><button className="back-link" onClick={() => void loadInvestigation()}>Oppdater status</button><button className="submit-button" onClick={startResearchPass} disabled={inflight || isActive}>{inflight ? "Starter …" : isActive ? "Research pågår …" : "Start research-pass"}<span aria-hidden="true">→</span></button></div>{stale && <p className="form-error" role="status">Data kan være utdatert. Siste lagrede status vises.</p>}{runStatus && <p className={runOk ? "form-success" : "form-error"} role="status">{runStatus}</p>}<div className="coverage-summary"><strong>{completedModules} / {enabledModules.length || 0}</strong><span>valgte moduler har fullført status</span>{research.summary && <span>Pass: {research.summary.executed} utført · {research.summary.blocked} blokkert · {research.summary.failed} feilet{research.summary.stopped_reason ? ` · stopp: ${research.summary.stopped_reason}` : ""}</span>}{research.error_code && <span>Feilkode: {research.error_code}</span>}</div><div className="coverage-list">{modules.length ? modules.map((item) => <div className="coverage-row" key={item.module}><div><strong>{item.module.replaceAll("_", " ")}</strong><span>{item.enabled ? item.status : "Ikke valgt"}{item.stop_reason ? ` · stopp: ${item.stop_reason}` : ""}</span>{coverageText(item.coverage) && <small>{coverageText(item.coverage)}</small>}</div><span className="status-dot" role="img" aria-label={item.status} /></div>) : <p className="empty-note">Ingen scope-moduler er valgt i denne saken.</p>}</div></section>
    <section className="detail-section"><div className="section-heading"><span>DATA</span><div><h2>Leads og entities</h2><p>Lagret status og identitetskontekst fra API-et.</p></div></div><div className="detail-list">{investigation.leads.map((lead) => <article className="lead-card" key={lead.id}><strong>{lead.lead_type}: {valueText(lead.value)}</strong><span>Status: {lead.status} · prioritet {lead.priority.toFixed(2)} · dybde {lead.depth}</span>{lead.reason && <p>{lead.reason}</p>}<small>Informasjonsbehov: {lead.information_need || "Ikke registrert"} · {lead.scope_area || "uten scope"} · {lead.trigger_type || "uten trigger"}{lead.blocked_reason ? ` · blokkert: ${lead.blocked_reason}` : ""}</small></article>)}</div>{investigation.leads.length === 0 && <p className="empty-note">Ingen leads er lagret i denne saken.</p>}<div className="detail-list">{investigation.entities.map((entity) => <article className="entity-card" key={entity.id}><strong>{entity.canonical_name || "Uten kanonisk navn"}</strong><span>{entity.schema} · oppløsning: {entity.resolution_state} · relasjonsdybde: {entity.relation_depth}</span><small>Ekspansjon: {entity.expansion_state}{entity.material_reason ? ` · ${entity.material_reason}` : ""}</small></article>)}</div></section>
    <section className="detail-section"><div className="section-heading"><span>CLAIMS</span><div><h2>Påstander og kildebelegg</h2><p>{investigation.document_count} dokumenter · {investigation.evidence_count} evidence-poster</p></div></div>{investigation.claims.length ? investigation.claims.map((claim) => <ClaimCard key={claim.id} claim={claim} investigationId={id} />) : <p className="empty-note">Ingen lagrede påstander.</p>}</section></main>;
}

function ClaimCard({ claim, investigationId }: { claim: ClaimState; investigationId: string }) {
  return <article className="claim-card"><div className="claim-header"><strong>{claim.predicate}</strong><span className={`claim-status claim-${claim.status.toLowerCase()}`}>{claimLabel[claim.status] || claim.status}</span></div><p>{valueText(claim.value)}</p><small>Opprettet: {formatDate(claim.created_at)}</small>{claim.evidence.length ? <div className="evidence-list">{claim.evidence.map((evidence) => { const source = safeHttpUrl(evidence.original_url) || safeHttpUrl(evidence.canonical_url); return <div className="evidence-card" key={`${evidence.evidence_id}:${evidence.relation}`}><strong>{evidence.relation} · {evidence.source_name || "Ukjent kilde"}</strong>{evidence.excerpt && <p>{evidence.excerpt}</p>}<small>Locator: {valueText(evidence.locator)} · hentet {formatDate(evidence.fetched_at)} · SHA-256: {evidence.sha256 || "ikke registrert"}</small><div className="evidence-links">{source && <a href={source} target="_blank" rel="noreferrer">Åpne originalkilde</a>}{evidence.raw_storage_key && <a href={`${API_BASE}/api/v1/investigations/${investigationId}/evidence/${encodeURIComponent(evidence.evidence_id)}/raw`}>Last ned lagret råkilde</a>}</div></div>; })}</div> : <p className="empty-note">Ingen lagret evidence for denne påstanden.</p>}</article>;
}
