"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

const modules = [
  ["WEB_MEDIA", "Offentlig web, medier og fagkilder"], ["BUSINESS_ROLES", "Virksomhetsroller og grunnkontekst"],
  ["COMPANY_NETWORK", "Konsern og selskapsrelasjoner"], ["FINANCIALS", "Årsregnskap og nøkkeltall"],
  ["ANNOUNCEMENTS_STATUS", "Kunngjøringer og registrert status"], ["HISTORICAL_WEB", "Historiske snapshots"],
  ["DOMAINS_DIGITAL", "Domener og digital infrastruktur"], ["PUBLIC_PROFILES", "Offentlig tilgjengelige profiler"],
  ["SANCTIONS", "Offisielle sanksjonslister"],
] as const;
const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

export default function Home() {
  const router = useRouter();
  const [targetType, setTargetType] = useState("person"), [name, setName] = useState(""), [birthDate, setBirthDate] = useState(""), [birthYear, setBirthYear] = useState(""), [place, setPlace] = useState(""), [knownBusinesses, setKnownBusinesses] = useState(""), [orgnr, setOrgnr] = useState(""), [purpose, setPurpose] = useState("");
  const [selectedModules, setSelectedModules] = useState<string[]>([]), [expansionPolicy, setExpansionPolicy] = useState("CONTEXT_ONLY"), [maxRelationDepth, setMaxRelationDepth] = useState("0"), [error, setError] = useState(""), [isSubmitting, setIsSubmitting] = useState(false);
  function toggleModule(module: string) { setSelectedModules((current) => current.includes(module) ? current.filter((item) => item !== module) : [...current, module]); }
  async function createInvestigation(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError("");
    if (!name.trim() || !purpose.trim()) { setError("Fyll inn navn og formål før du oppretter undersøkelsen."); return; }
    setIsSubmitting(true); const target: Record<string, string> = { type: targetType, name: name.trim() };
    if (birthDate) target.birth_date = birthDate; else if (birthYear) target.birth_year = birthYear; if (place.trim()) target.place = place.trim(); if (knownBusinesses.trim()) target.known_organizations = knownBusinesses.trim(); if (orgnr.trim()) target.known_orgnrs = orgnr.trim();
    try {
      const response = await fetch(`${API_BASE}/api/v1/investigations`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ target, purpose: purpose.trim(), scope_modules: selectedModules, expansion_policy: expansionPolicy, max_relation_depth: Number(maxRelationDepth) }) });
      const payload = await response.json().catch(() => null); if (!response.ok) { const detail = Array.isArray(payload?.detail) ? payload.detail.map((item: { msg?: string }) => item.msg).filter(Boolean).join(" ") : payload?.detail; throw new Error(detail || "Kunne ikke opprette undersøkelsen."); }
      const id = payload?.id || payload?.uuid; if (!id) throw new Error("API-et returnerte ingen undersøkelses-ID."); router.push(`/investigations/${id}`);
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Noe gikk galt. Prøv igjen."); setIsSubmitting(false); }
  }
  function changeTargetType(value: string) { setTargetType(value); setExpansionPolicy(value === "person" ? "CONTEXT_ONLY" : "DIRECT_RELATIONS"); setMaxRelationDepth(value === "person" ? "0" : "1"); }
  return <main className="site-shell"><header className="topbar"><a className="brand" href="/" aria-label="Analysen hjem"><span className="brand-mark">A</span> ANALYSEN</a><span className="topbar-note">Kildebevisst OSINT</span></header><div className="page-grid">
    <section className="intro"><p className="eyebrow">NY UNDERSØKELSE</p><h1>Start med et tydelig spørsmål.</h1><p className="intro-copy">Velg mål, formål og kilder. Analysen viser alltid hva som er undersøkt, hva som mangler og hvor funnene kommer fra.</p><div className="principles" aria-label="Prinsipper"><div><span>01</span><p>Primærkilder først</p></div><div><span>02</span><p>Ingen automatisk ekspansjon</p></div><div><span>03</span><p>Alle påstander kan etterprøves</p></div></div></section>
    <form className="investigation-form" onSubmit={createInvestigation} noValidate><div className="form-section"><div className="section-heading"><span>01</span><div><h2>Mål</h2><p>Hvem eller hva skal undersøkes?</p></div></div><div className="field-grid two-col"><label>Type<select value={targetType} onChange={(event) => changeTargetType(event.target.value)}><option value="person">Person</option><option value="organization">Organisasjon</option><option value="company">Virksomhet</option><option value="domain">Domene</option></select></label><label>Navn eller identifikator <span className="required">*</span><input required minLength={3} value={name} onChange={(event) => setName(event.target.value)} placeholder="For eksempel Kari Nordmann" /></label><label>Fødselsdato <span className="optional">valgfritt</span><input type="date" value={birthDate} onChange={(event) => setBirthDate(event.target.value)} /></label><label>Fødselsår <span className="optional">valgfritt</span><input inputMode="numeric" value={birthYear} onChange={(event) => setBirthYear(event.target.value)} placeholder="For eksempel 1984" /></label></div><label>Sted <span className="optional">valgfritt</span><input value={place} onChange={(event) => setPlace(event.target.value)} placeholder="Kommune eller land" /></label>{targetType === "person" ? <label>Kjente virksomheter <span className="optional">valgfritt</span><input value={knownBusinesses} onChange={(event) => setKnownBusinesses(event.target.value)} placeholder="Navn på virksomhet" /></label> : <label>Organisasjonsnummer <span className="optional">valgfritt</span><input value={orgnr} onChange={(event) => setOrgnr(event.target.value)} placeholder="For eksempel 987 654 321" /></label>}</div>
      <div className="form-section"><div className="section-heading"><span>02</span><div><h2>Formål og omfang</h2><p>Et konkret formål gjør resultatet etterprøvbart.</p></div></div><label>Hva skal undersøkelsen avklare? <span className="required">*</span><textarea required minLength={3} value={purpose} onChange={(event) => setPurpose(event.target.value)} rows={3} placeholder="Beskriv beslutningen eller spørsmålet undersøkelsen skal belyse." /></label><fieldset><legend>Undersøkelsesområder <span className="optional">valgfritt</span></legend><p className="field-help">Velg aktivt. Et tomt scope oppretter saken uten research-områder.</p><div className="module-list">{modules.map(([module, description]) => <label className={`module-option ${selectedModules.includes(module) ? "selected" : ""}`} key={module}><input type="checkbox" checked={selectedModules.includes(module)} onChange={() => toggleModule(module)} /><span><strong>{module.replaceAll("_", " ")}</strong><small>{description}</small></span></label>)}</div></fieldset></div>
      <div className="form-section"><div className="section-heading"><span>03</span><div><h2>Relasjoner</h2><p>Sett en grense for hvor langt spor kan følges.</p></div></div><div className="field-grid two-col"><label>Ekspansjonspolitikk<select value={expansionPolicy} onChange={(event) => setExpansionPolicy(event.target.value)}><option value="CONTEXT_ONLY">Kun kontekst</option><option value="DIRECT_RELATIONS">Direkte relasjoner</option><option value="MATERIAL_RELATIONS">Vesentlige relasjoner</option></select></label><label>Maks relasjonsdybde<select value={maxRelationDepth} onChange={(event) => setMaxRelationDepth(event.target.value)}><option value="0">0 — kun mål</option><option value="1">1 — direkte</option><option value="2">2 — to ledd</option><option value="3">3 — tre ledd</option></select></label></div><p className="privacy-note"><span aria-hidden="true">◌</span> Du velger selv omfanget. Identitetsavklaring er alltid begrenset til det som er nødvendig for å skille riktige kilder fra feil person eller virksomhet.</p></div>
      {error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button className="submit-button" type="submit" disabled={isSubmitting}>{isSubmitting ? "Oppretter …" : "Opprett undersøkelse"}<span aria-hidden="true">→</span></button><p>Etter opprettelse kan du starte research-passer fra undersøkelsessiden.</p></div>
    </form></div></main>;
}
